// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blxtkcbvpfjjiyhgyzpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJseHRrY2J2cGZqaml5aGd5enBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTY0ODIsImV4cCI6MjA1NzIzMjQ4Mn0.ie_fm5uDkmtJChISkYdIgqC8cfZ0NnLTSn6yR9qB55g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);